version: '3'

services:
  namenode:
    build: .
    container_name: namenode
    hostname: namenode
    ports:
      - "9870:9870"   # Hadoop NameNode web UI
      - "8088:8088"   # YARN ResourceManager web UI
      - "9000:9000"   # HDFS
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
      - SPARK_HOME=/usr/local/spark
    volumes:
      - ./data:/data
      - ./hadoop_data:/hadoop_data
      - ./logs:/usr/local/hadoop/logs